### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by kasra-hosseini** [alan-turing-institute/QUIPP-collab#119] opened 2020-10-21 17:13 UTC
Greg and I get different results (synthetic datasets and consequently, disclosure risk scores) when running synthpop on one config file. We set the seed manually in the `run` file, but this did not solve the problem. We are using the same version of R (4.0.3) and synthpop (1.6-0).

**Comment by kasra-hosseini** [comment] 2020-10-22 10:34
I changed the title of this issue as it seems the issue is from the generator rather than synthpop. @gmingas reported that the generator outputs similar datasets except for one column (in this example dataset: `generator-outputs/odi-nhs-ae/hospital_ae_data_deidentify`). Since that one column changes in each run of generator, synthpop produces different results.

**Comment by gmingas** [comment] 2020-10-22 14:38
There seem to be other reproducibility issue when using CTGAN and synthpop on the polish data set. Exploring now.

**Comment by gmingas** [comment] 2020-10-27 14:11
It turns out CTGAN random results [are not reproducible](https://github.com/sdv-dev/CTGAN/issues/63). We would have to fork and edit the code or create a PR in their repo to fix this.

Also, two of the classifiers we use in classifiers.py to calculcate utility are not reproducible (KNeighboursClassifier and RandomForestClassifier). The former does not take a random state argument and the latter does but it looks like it does not work.

**Comment by ots22** [comment] 2020-11-24 11:01
Can we close this (perhaps as can't/won't fix?)

**Closed** 2020-11-24 11:26 UTC
